CREATE TABLE chicken_meals(id SERIAL PRIMARY KEY, name VARCHAR(60));
CREATE TABLE meat_meals(id SERIAL PRIMARY KEY, name VARCHAR(60));
CREATE TABLE fish_meals(id SERIAL PRIMARY KEY, name VARCHAR(60));
CREATE TABLE veg_meals(id SERIAL PRIMARY KEY, name VARCHAR(60));
